#!/bin/bash

set -e

if [ -f local.cfg ]; then
    CONFIG="-c local.cfg"
elif [ -f my-buildout.cfg ]; then
    CONFIG="-c my-buildout.cfg"
else
    CONFIG=
fi

if [ ! -x ./venv/bin/buildout ]; then
    read -ep "No buildout found. Bootstrap with python version [2.7] " VERSION
    if [ -z "$VERSION" ]; then
        VERSION="2.7"
    fi
    virtualenv --python=python$VERSION venv
    venv/bin/pip install -U setuptools
    BINARY="venv/bin/python"
    #BOOTSTRAP="bootstrap.py"
    #if [ ! -f bootstrap.py ]; then
    #    BOOTSTRAP="config/bootstrap.py"
    #fi
    #$BINARY $BOOTSTRAP
    venv/bin/pip install zc.buildout
fi

venv/bin/buildout $CONFIG "$@"

#~/bin/tags
