#!/bin/bash

set -e
export GOCEPT_SELENIUM_HEADLESS=true
export GOCEPT_SELENIUM_TIMEOUT=20
if [ -x ./test.sh ]; then
    ./test.sh $@
elif [ -x ./bin/py.test ]; then
    ./bin/py.test $@
elif [ -x ./venv/bin/py.test ]; then
    ./venv/bin/py.test $@
elif [ -x ./bin/test ]; then
    ./bin/test $@
elif [ -f ./docker-compose.yml ]; then
    docker-compose exec wsgi pytest $@
else
    read -ep "No test executable found. Specify path " PATH
    ./$PATH
fi
